# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lint, Build, and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
    - run: yarn lint:lockfile
    - run: yarn lint:version
    - run: yarn lint
    - run: yarn build
    - name: Test echo-db
      run: yarn coverage
      working-directory: ./packages/echo-db
    - name: Test echo-demo
      run: yarn coverage
      working-directory: ./packages/echo-demo
    - name: Test echo-protocol
      run: yarn coverage
      working-directory: ./packages/echo-protocol
    - name: Test echo-testing
      run: yarn coverage
      working-directory: ./packages/echo-testing
    - name: Test model-factory
      run: yarn coverage
      working-directory: ./packages/model-factory
    - name: Test object-model
      run: yarn coverage
      working-directory: ./packages/object-model
    - name: Test text-model
      run: yarn coverage
      working-directory: ./packages/text-model
    - name: Test util
      run: yarn coverage
      working-directory: ./packages/util
